<?php

  /**
  * EcomExpress
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the Open Source License (OSL 3.0)
  * It is also available through the world-wide-web at this URL:
  * http://opensource.org/licenses/osl-3.0.php
  *
  * @category    Ecom
  * @package     Ecom_Express
  * @author      Ecom Dev Team <developer@ecomexpress.com >
  * @copyright   Copyright EcomExpress (http://ecomexpress.com/)
  * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
  */


?>
<?php 

$order_id = Mage::app()->getRequest()->getParam('order_id');
$current_shipping_method = Mage::getModel('sales/order')
->load($order_id)
->getShippingMethod();

?>
<?php $_order = $this->getOrder() ;
?>
<h1><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h1>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<div class="col2-set">

    <?php if (!$_order->getIsVirtual()): ?>
    <div class="col-1">
          <?php  if(strcmp($current_shipping_method, 'ecomexpress_ecomexpress') == true){    ?>
    	 <h2><?php echo $this->__('Shipping Address'); } else {?></h2>
         <h2><?php echo $this->__('Ship From'); }?></h2>
        
        
         <?php  if(strcmp($current_shipping_method, 'ecomexpress_ecomexpress') == true){    ?>
        <address><?php echo $_order->getShippingAddress()->format('html');} else{ ?></address>
        
        <address><?php
        echo Mage::getStoreConfig('general/store_information/name'); echo"<br/>";
        echo Mage::getStoreConfig('shipping/origin/street_line1').", " .Mage::getStoreConfig('shipping/origin/street_line2');echo"<br/>";
        echo Mage::getStoreConfig('shipping/origin/city').", ".Mage::getStoreConfig('shipping/origin/region_id').", ".Mage::getStoreConfig('shipping/origin/postcode');echo"<br/>";
        echo Mage::app()->getLocale()->getCountryTranslation(Mage::getStoreConfig('shipping/origin/country_id'));echo"<br/>";
        echo "T:".Mage::getStoreConfig('general/store_information/phone');echo"<br/>";
    	}
        ?>
        
        </address>
    </div>
    <div class="col-2">
    <?php else: ?>
    <div class="col-1">
    <?php endif; ?>
        <h2><?php echo $this->__('Billing Address') ?></h2>
        <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
    </div>
<?php if (!$_order->getIsVirtual()): ?>
</div>
<div class="col2-set">
    <div class="col-1">
        <h2><?php echo $this->__('Shipping Method') ?></h2>
         <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
    </div>
<?php endif; ?>
    <div class="col-2">
        <h2><?php echo $this->__('Payment Method') ?></h2>
        <?php echo $this->getPaymentInfoHtml() ;?>
    </div>
</div>
<h2><?php echo $this->__('Items Ordered') ?></h2>
<table class="data-table" id="my-orders-table">
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th><?php echo $this->__('SKU') ?></th>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <th class="a-center"><?php echo $this->__('Qty') ?></th>
            <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <tfoot>
        <?php  echo $this->getChildHtml('order_totals'); ?>
    </tfoot>
    <?php $_items = $_order->getItemsCollection(); ?>
    <?php $_count = $_items->count();  ?>
    <?php foreach ($_items as $_item): ?>
    <?php if ($_item->getParentItem()) continue; ?>
    <tbody>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
        <?php endforeach; ?>
</table>
<script type="text/javascript">decorateTable('my-orders-table', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<script type="text/javascript">window.print();</script>
